/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.9.0
 *
 * Project: 'M55_HE.Release+Alif-AppKit-E7'
 * Target:  'Release+Alif-AppKit-E7'
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/*
 * Define the Device Header File:
 */
#define CMSIS_device_header         "alif.h"

/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.0 */
#define RTE_CMSIS_RTOS2             /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5        /* CMSIS-RTOS2 Keil RTX5 */
#define RTE_CMSIS_RTOS2_RTX5_SOURCE /* CMSIS-RTOS2 Keil RTX5 Source */
/* AlifSemiconductor::CMSIS Driver:GPIO@1.0.0 */
#define RTE_Drivers_GPIO            1 /* Driver GPIO */
/* AlifSemiconductor::CMSIS Driver:VIO:Board&AppKit-E7-AIML@1.0.0 */
#define RTE_VIO_BOARD
#define RTE_VIO_APPKIT_E7_AIML
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@2.0.0 */
#define RTE_Drivers_LL_PINCONF /* Driver PinPAD and PinMux */

#endif /* RTE_COMPONENTS_H */
